---
id: 4cbca208-2e82-4b68-bbb7-ab82263f63a8
registrations:
  - validity:
      - input:
          class:
            id: 8e80de8b-4c8c-42ca-8ddd-cec816a955fa
            name: Process Configuration
          process:
            id: ebef98ea-f81e-449a-b4ea-8d6cfe66e99d
            name: ReConnect Opus Import
          specification:
            id: a3cd43b2-8d42-445f-920d-459205df4b3e
            name: ReConnect Opus Integration Spec
        from: 2018-01-01T00:00:00.000Z
...
